-- Migration V29: Clear synthetic placeholder audio data generated by previous fallback
-- Ensures only genuine voice recordings are served to users

UPDATE standups
SET audio_data = NULL
WHERE audio_content_type = 'audio/wav'
  AND (audio_file_name LIKE '%.webm' OR audio_file_name LIKE '%.mp4' OR audio_file_name LIKE '%.ogg' OR audio_file_name IS NULL);
