package com.jvmcrew.model.enums;

public enum NotificationType {
    TASK_ASSIGNED,
    TASK_REASSIGNED,
    TASK_SUBMITTED,
    TASK_APPROVED,
    TASK_CHANGES_REQUESTED,
    HOMEWORK_PUBLISHED,
    HOMEWORK_DEADLINE_CHANGED,
    HOMEWORK_REVIEWED,
    HOMEWORK_SOLUTION_PUBLISHED,
    STANDUP_SUBMITTED,
    STANDUP_ANSWERED,
    STANDUP_REMINDER,
    TEAM_UPDATE
}
